name: CI - Backend Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: bas
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false


     
      - name: Verify conda env
        run: conda info --envs

   
      - name: Install pytest
        run: conda install -y pytest

      
      - name: Run tests
        run: pytest -v
